### ISSUE TITLE
Drop support for PostgreSQL 8.2

### ISSUE THREAD

**Issue by dvarrazzo** [reorg/pg_reorg#12]
It's been unsupported for a while and clutters up the codebase with `#define`s

A commit 370e572c is in master, I assume that's enough as cleanup. Maybe there should be a guard in one of the entry point functions and/or the binary.

**Comment by schmiddy** [comment]
Here's another reason to remove 8.2 support: trying to build git master against 8.2.23 gives me this error:

Undefined symbols:
  "_PQconnectionNeedsPassword", referenced from:
      _pgut_connect in pgut.o

since PQconnectionNeedsPassword() was apparently introduced only in 8.3. I am no Makefile guru, but could we tell the Makefile to exit with an error if pg_config reports a version older than 8.3?

There are also a few more lines like
  #if PG_VERSION_NUM >= 80300
we could get rid of in ./lib/reorg.c.

**Comment by schmiddy** [comment]
Looking around at a few other extensions (e.g. pgtap, json_91), it seems common to have the Makefile check pg_config for a compatible version string and bail out if the version isn't supported. Here's a patch to our Makefile:
  https://gist.github.com/3903770

including the cruft-removal from ./lib/reorg.c I mentioned. If the Makefile is enforcing the proper version, I don't think it's necessary to put a guard in the binary or library as well, is it? (Although I don't think it would hurt.) It's possible that someone would build pg_reorg on 8.3+, then try to use it against an older server version, but they should just get the error message complaining about the pg_reorg libraries/extension not being installed on the server in that case.

Now that I think about it, a related issue is: should we try to warn or guard against someone using a pg_reorg binary against a different library version, as reported by reorg.version(), installed on the server? Although this might work in some cases if the library hasn't changed much, it seems dangerous to allow in general.

**Comment by dvarrazzo** [comment]
On Wed, Oct 17, 2012 at 6:06 AM, schmiddy notifications@github.com wrote:

> Looking around at a few other extensions (e.g. pgtap, json_91), it seems
> common to have the Makefile check pg_config for a compatible version string
> and bail out if the version isn't supported. Here's a patch to our Makefile:
> https://gist.github.com/3903770

This is somewhat more idiomatic as a bail-out test but nothing major:

```
ifneq ($(shell echo $(VERSION) | grep -E "^7\.|^8\.[012]"),)
```

> Now that I think about it, a related issue is: should we try to warn or
> guard against someone using a pg_reorg binary against a different library
> version, as reported by reorg.version(), installed on the server? Although
> this might work in some cases if the library hasn't changed much, it seems
> dangerous to allow in general.

 I'd thought about the same: I think the executable should check the
version of the library and bail out in case of mismatch. It seems dangerous
to me too.

**Comment by schmiddy** [comment]
OK, I've committed the Makefile change with your cleaner version check in 6c8c5327019. I could have time to put in a binary version check vs. library version check in the next day or two, or feel free to tackle it yourself if you're in the mood.

**Comment by dvarrazzo** [comment]
Better talk about the version check in another ticket...

**Comment by dvarrazzo** [comment]
Grep for 80300 returns no more row, so I assume all the 8.2 macros are gone.
