### ISSUE TITLE
Consistency check between program and library

### ISSUE THREAD

**Issue by dvarrazzo** [reorg/pg_reorg#13]
pg_reorg can run against a database where an older version of the extension is loaded, with undefined results.

I've started a branch to check for discrepancies between the executable and the library. I've committed a [preliminary patch](https://github.com/dvarrazzo/pg_reorg/commit/0be414ad10c32d6759f35782ca0b16fb2d3e2127) to clean up the errors handling in reorg_one_database, allowing it to return any error and making the output of the program more consistent between the --all and --dbname modes. Following patches address the version check.

The current check is between the pg_reorg binary and the library, as reorg.version() is implemented in C. This doesn't address the discrepancy between the binary/library and the sql schema, that is probably more likely (just make+make install in a db where pg_reorg was already installed and there it is).

Note that I'm working at this branch in my [local repos](https://github.com/dvarrazzo/pg_reorg): in case these patches are rejected I don't like the reorg repos to be cluttered with my experiments.

**Comment by schmiddy** [comment]
Oh, I just happened to re-read this issue and noticed your commit 0be414ad10. I have a large patch I'm cleaning up for the multiple_tables branch which whacks around reorg_one_database() to allow processing of multiple tables with the possibility of table(s) failing and not bailing out with exit(). I think I'll try to merge your patch in via a subsequent commit.

**Comment by dvarrazzo** [comment]
Added consistency check between binary and sql too. Merged to master and to maint_1.1. Released in pg_repack 1.1.8 beta2.
