### ISSUE TITLE
Compile warnings about appendStringInfoVA and appendStringInfoVA_s

### ISSUE THREAD

**Issue by schmiddy** [reorg/pg_reorg#14]
I'd like to get rid of this compile warning:

```
pgut/pgut.c: In function ‘appendStringInfoVA’:
pgut/pgut.c:1174: warning: function might be possible candidate for ‘printf’ format attribute
...
pgut/pgut-spi.c: In function ‘appendStringInfoVA_s’:
pgut/pgut-spi.c:27: warning: function might be possible candidate for ‘printf’ format attribute
```

As described here:
  http://lists.pgfoundry.org/pipermail/reorg-general/2012-September/000077.html

**Comment by dvarrazzo** [comment]
Doesn't it need compiler guards where the attribute is not supported? Windows, compilers other than gcc etc.

(looking at PG source...) Ah, I thought there was some autoconf spell to configure the related macros, but it's easier than that: from [pg_config_manual.h](https://github.com/postgres/postgres/blob/04a37a5716867f8eade144baac847a9737ac22f5/src/include/pg_config_manual.h#L156)

```
/*
 * Set the format style used by gcc to check printf type functions. We really
 * want the "gnu_printf" style set, which includes what glibc uses, such
 * as %m for error strings and %lld for 64 bit long longs. But not all gcc
 * compilers are known to support it, so we just use "printf" which all
 * gcc versions alive are known to support, except on Windows where
 * using "gnu_printf" style makes a dramatic difference. Maybe someday
 * we'll have a configure test for this, if we ever discover use of more
 * variants to be necessary.
 */
#ifdef WIN32
#define PG_PRINTF_ATTRIBUTE gnu_printf
#else
#define PG_PRINTF_ATTRIBUTE printf
#endif
```

So it seems it would be no problem to define a macro the same way, barred the same "maybe someday". OTOH if we don't "really want" the gnu_printf your patch is perfectly fine.

**Comment by schmiddy** [comment]
I figured that just using "printf" attribute directly was okay because
1. pg_reorg already did so in a few places
2. Postgres code before 9.1 did so

plus, I wasn't sure I should be adding a WIN32-specific hack, since I have no easy way to test it. That said, it certainly seems like we could include that snippet you show when building against PG < 9.1, and switch to using PG_PRINTF_ATTRIBUTE instead of printf.

**Comment by dvarrazzo** [comment]
I don't think it's worth: I don't know what gnu_printf would buy me, hence I don't need it ;)

**Comment by dvarrazzo** [comment]
I've backported the patch to maint 1.1 too. Issue closed, thank you
