### ISSUE TITLE
reorg_drop() with nonexistent OID causes crash

### ISSUE THREAD

**Issue by schmiddy** [reorg/pg_reorg#20]
reorg_drop() will cause a backend crash when passed a table OID which does not exist, due to get_quoted_relname() and get_quoted_nspname() dereferencing a NULL pointer. 

```
josh@[local] [test] # select reorg.reorg_drop(9999);
The connection to the server was lost. Attempting reset: Failed.
```

This is particularly bad, because even non-superusers who have USAGE on the reorg schema may execute reorg_drop() with a bogus argument, and get a crash before the must_be_superuser() check kicks in. I see the 1.1 milestone is closed, but perhaps the fix, which should be forthcoming shortly, should be shoehorned in.

**Comment by schmiddy** [comment]
The simple fix is in 5ecb00c -- only in multiple_tables branch at the moment, but should be applied to master as well and possibly maint_1.1.

**Comment by dvarrazzo** [comment]
Of course we can apply to 1.1 too. The milestone was closed automatically because all its tickets were closed, but that hasn't any official meaning. I will backport the patch to the other branches.

**Comment by dvarrazzo** [comment]
All merged, thank you
