### ISSUE TITLE
Add DURATION to debug logging....

### ISSUE THREAD

**Issue by sean-** [reorg/pg_reorg#21]
'ello.

Would it be possible to add in either a BEGIN and END timestamp to various operations? For instance:

```
DEBUG: sql_pop        : DELETE FROM reorg.log_19533 WHERE id <= $1
DEBUG: ---- setup ----
DEBUG: ---- copy tuples ----
DEBUG: ---- create indexes ----
DEBUG: [0]
DEBUG: target_oid   : 20924
DEBUG: create_index : CREATE INDEX index_20924 ON reorg.table_19533 USING btree ("colA", colB)
```

How long did it take for the `copy tuples` step take? It'd be useful to know when that happened so that we could line up that particular event with other activities in the system. As is, we just have to blindly assume. Not a huge problem, but it would be a very big "nice to have".  A duration would be nice, too.

**Comment by schmiddy** [comment]
I agree that it'd be useful to know durations, although I think it'd be enough to just print a timestamp with each message -- you can deduce the duration of the steps from there. 

The logging from pg_reorg is rather slapdash at the moment, with a mix of printf(), fprintf(stderr, ... ), elog() and ereport() calls. We should try to standardize these. It's too bad there doesn't seem to be an equivalent of log_line_prefix for messages displayed to the client, that would provide an easy solution.

**Comment by dvarrazzo** [comment]
as pg_reorg is not a long running program but something to be run occasionally from command line (or at most from crontab), a heavyweight configuration of the message logging is outside its scope. Please use a command line tool such as "ts" from "moreutils" to attach timestamps to the logged line:

```
$ pg_repack --elevel DEBUG contrib_regression 2>&1 | ts "%H:%M:%.S"
23:16:01.935913 DEBUG: ---- repack_one_table ----
23:16:01.936131 DEBUG: target_name    : tbl_cluster
23:16:01.936182 DEBUG: target_oid     : 36856
23:16:01.936217 DEBUG: target_toast   : 37418
23:16:01.936249 DEBUG: target_tidx    : 37420
23:16:01.936282 DEBUG: pkid           : 36862
23:16:01.936314 DEBUG: ckid           : 36864
23:16:01.936349 DEBUG: create_pktype  : CREATE TYPE repack.pk_36856 AS (col1 integer, ","")" text)
23:16:01.936383 DEBUG: create_log     : CREATE TABLE repack.log_36856 (id bigserial PRIMARY KEY, pk repack.pk_36856, row tbl_cluster)
...
```

**Comment by sean-** [comment]
> as pg_reorg is not a long running program but something to be run occasionally from command line (or at most from crontab), a heavyweight configuration of the message logging is outside its scope. Please use a command line tool such as "ts" from "moreutils" to attach timestamps to the logged line:
> 
> $ pg_repack --elevel DEBUG contrib_regression 2>&1 | ts "%H:%M:%.S"
> 23:16:01.935913 DEBUG: ---- repack_one_table ----
> 23:16:01.936131 DEBUG: target_name    : tbl_cluster
> 23:16:01.936182 DEBUG: target_oid     : 36856
> 23:16:01.936217 DEBUG: target_toast   : 37418
> 23:16:01.936249 DEBUG: target_tidx    : 37420
> 23:16:01.936282 DEBUG: pkid           : 36862
> 23:16:01.936314 DEBUG: ckid           : 36864
> 23:16:01.936349 DEBUG: create_pktype  : CREATE TYPE repack.pk_36856 AS (col1 integer, ","")" text)
> 23:16:01.936383 DEBUG: create_log     : CREATE TABLE repack.log_36856 (id bigserial PRIMARY KEY, pk repack.pk_36856, row tbl_cluster)
> ...
> Gah. I suppose I can abdicate to using svlogd(1) from the runit package, but it hadn't occurred to me to do that. Is punting to svlogd(1) the right thing? I'm skeptical, but accept the answer - I just hadn't thought of piping the output through svlogd(1). I don't run any Linux anywhere in production so using ts(1) doesn't work terribly well (is ts(1) even a normal app under Linux?), though I do confess to running most of my PostgreSQL instances under runit.  From a doc perspective, it's probably a nice thing to point out alternatives.

% uname 
FreeBSD
% which ts
ts: Command not found.
Exit 1
% uname 
Darwin
% which ts
ts: Command not found.
% which  ts
no ts in /root/bin /opt/local/sbin /opt/local/bin /usr/local/sbin /usr/local/bin /usr/ccs/bin /usr/openwin/bin /usr/sfw/bin /usr/sbin /usr/bin /usr/xpg4/bin /opt/local/sbin /opt/local/bin /usr/openwin/bin /usr/ccs/bin /usr/ucb /usr/sfw/bin /usr/bin /bin /usr/xpg4/bin /opt/local/sbin /opt/local/bin
Exit 1
% uname
SunOS

And even then, runit is a module from macports or sysutils/runit on FreeBSD. -sc

## 

Sean Chittenden
sean@chittenden.org

**Comment by dvarrazzo** [comment]
As I said, ts is part of the moreutils package (http://joeyh.name/code/moreutils/), which has several ports in itself. ts, specifically, is a ~100 lines perl script, good part of which is doc (https://github.com/madx/moreutils/blob/master/ts).

Honestly, it's not that hard rolling your timestamping script: it's a couple of line is any scripting language, which is a solution customizable to no end. Timestamping provided by the program will always miss that other option one wanted.
