### ISSUE TITLE
Use ALTER TABLE ... ENABLE ALWAYS so pg_reorg can operate on a Slony slave node

### ISSUE THREAD

**Issue by dvarrazzo** [reorg/pg_reorg#4]
http://pgfoundry.org/pipermail/reorg-general/2012-October/000094.html

**Comment by dvarrazzo** [comment]
I think the patch is good, with the only quirk that the function, macro, log message etc. are called alter_table, which is a tad too generic. Ok if I rename everything to "enable_trigger"?

**Comment by schmiddy** [comment]
On Nov 11, 2012 7:07 PM, "Daniele Varrazzo" notifications@github.com
wrote:

> I think the patch is good, with the only quirk that the function, macro,
> log message etc. are called alter_table, which is a tad too generic. Ok if
> I rename everything to "enable_trigger"?

Sure.

**Comment by dvarrazzo** [comment]
Rename done, I think the issue is fixed.

**Comment by dvarrazzo** [comment]
Backported to pg_repack 1.1.8 beta2 too.
