### ISSUE TITLE
Column name quoting

### ISSUE THREAD

**Issue by dvarrazzo** [reorg/pg_reorg#6]
http://pgfoundry.org/pipermail/reorg-general/2012-September/000071.html

**Comment by dvarrazzo** [comment]
Looks like some of the support is in the 'master' branch (bc20ace3). Is that enough?

Is it related to the [table-escape branch](https://github.com/reorg/pg_reorg/commits/table-escape)? Should the latter be a separate ticket?

**Comment by dvarrazzo** [comment]
Read the above ML thread. Very strange the issue is not repeatable. I wanted to add a test for it but as reported it doesn't normally show.

**Comment by schmiddy** [comment]
I think the table-escape branch was mostly a mistake on my part -- I was making the same mistake as the recent poster here:
  http://comments.gmane.org/gmane.comp.db.postgresql.bugs/30872

assuming that pg_reorg should be handling escaping of table names passed to the program, when in fact it is standard (if undocumented) for such utilities to assume you have escaped the table name already. I haven't double checked, but we might be able to just get rid of the table-escape branch if there are no other fixes in it.

About the bug with the column name ("order") not being escaped -- yeah, the unreproducibility was kind of mystifying. I think the fix in bc20ace32bfa17 is pretty reasonable/safe, though.

**Comment by schmiddy** [comment]
I deleted the table-escape branch, after checking that there were no useful commits there which needed to be merged into master. AFAICT pg_reorg's table escaping, particularly the interpretation of the --table argument, works the same as similar Postgres tools, such as clusterdb.

**Comment by dvarrazzo** [comment]
The fix is both in maint 1.1 and master.
