### ISSUE TITLE
Deal with invalid indexes

### ISSUE THREAD

**Issue by dvarrazzo** [reorg/pg_reorg#9]
pg_reorg chokes when an invalid index is left behind e.g. by CREATE INDEX CONCURRENTLY: 
http://pgfoundry.org/pipermail/reorg-general/2012-October/000101.html

**Comment by dvarrazzo** [comment]
Ouch, I've noticed just now Josh had already prepared a patch for the issue. Let's see what's the difference...

**Comment by dvarrazzo** [comment]
I've added another commit 0a87822 where reorg.primary_keys avoids returning an invalid index as pkey. I think with this commit my patches and Josh patch are equivalent (mine adds a warning reporting the skipped indexes definition too)

**Comment by schmiddy** [comment]
That looks fine, and I think your warning message is helpful.

At first, I was a little unsure of whether we needed to be checking _indisready_ as well, but from looking at ./catalog/index.c and ./commands/indexcmds.c I believe it is enough to check _indisvalid_, as _indisvalid_ should only be set true after _indisready_ is true.

**Comment by dvarrazzo** [comment]
Backported from master to maint 1.1
